name: Fix Report
description: File a fix report
title: "[Fix]: "
labels: ["bug", "triage", "fix"]
assignees:
  - nabeel-shakeel
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this fix report! To address this fix as fast as possible, we need some information
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. nabeel.shakeel@techwards.co
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: markdown
    attributes:
      value: '## Screenshots'
  - type: markdown
    attributes:
      value: Add screenshot of bug or point to the portion where you want to fix